### ISSUE TITLE
Is it possible to hide a "shulker head"?

### ISSUE THREAD

**Issue by Lemar98** [SkytAsul/GlowingEntities#15]
Hello
Is it possible to make it so that I can glow the blocks and these heads will not be visible? After studying the source code, I realized that this is most likely impossible due to the limitations of Minecraft.
I need to glow Banner's and these shulker heads can be seen through the banner.
Maybe there is some kind of loophole?
![image](https://github.com/SkytAsul/GlowingEntities/assets/45980309/644922b1-359b-4604-bd70-cd76910fa788)

**Comment by SkytAsul** [comment]
Unfortunately no, as you said it's a limitation of Minecraft. Maybe you could investigate if a display entity could be used.
