### ISSUE TITLE
Older 1.20 versions unsupported

### ISSUE THREAD

**Issue by Agus5534** [SkytAsul/GlowingEntities#16]
Hello! I would like to report a couple of bugs with the use of versions prior to 1.20.5 (`GlowingEntities` class)!

Mainly, `watcherGet` does not contain the `al` method. According to what I checked, there is not the previous adaptation that existed (it may not be this). 
Finally, another error occurs in the `DataWatcher subclass` declaration (line **421**) because the condicional is erroneous, currently it is `version >= 20 || (version == 20 && versionMinor >= 5)`, where `version >= 20` must be `version > 20`

Thank you for your work, it is a great dependency and of very good quality!

**Comment by Agus5534** [comment]
Extra: I didn't try it on older versions (1.19...)

**Comment by SkytAsul** [comment]
May you try with this commit? :)

**Comment by Agus5534** [comment]
Yeaa thanks <3
