### ISSUE TITLE
1.21 Paperweight mappings not working

### ISSUE THREAD

**Issue by OakLoaf** [SkytAsul/GlowingEntities#18]
I am trying to use 1.3.5 and it is only displaying a blue glow colour, I have migrated to the new group name in the dependency and it is correctly importing, when looking at the library within my source code I can see that there is mappings for 1.21 but when running the code I get the following logs in my console:

```
[GlowingEntities] [GlowingEntities] Found server version 1.21.0
[GlowingEntities] [GlowingEntities] Loaded not matching version of the mappings for your server version
[GlowingEntities] [GlowingEntities] Loaded mappings V1_20_5_REMAPPED
```

**Comment by SkytAsul** [comment]
I guess you are using a paper plugin? Using the remapped 1.21 environment?

**Comment by OakLoaf** [comment]
I do not use any nms in the project currently other than GlowingEntities but it is being ran on Paper 1.21 (Experimental Builds)

**Comment by SkytAsul** [comment]
Yes but is it a paper plugin or spigot plugin?

**Comment by OakLoaf** [comment]
It is a Paper plugin but does not use the `paper-plugin.yml` and is not remapped on compilation.

**Comment by SkytAsul** [comment]
I guess you are using the paperweight gradle plugin and your JAR gets compiled with the `paperweight-mappings-namespace` manifest attribute set `mojang`. Please change it to `spigot`. See PaperMC documentation: https://docs.papermc.io/paper/dev/project-setup#plugin-remapping.

**Comment by SkytAsul** [comment]
It's probably not coming in the following days (I hope in a few weeks), because I don't have much time and it requires quite a refactoring (all classes have been renamed and other things like that). I started creating an util that will help in the future.

**Comment by OakLoaf** [comment]
Apologies for the late response. I depend on the paper-api but I don't use any of the paperweight plugins, I just compile with `shadowJar`, what logs in particular are you looking for? Just startup?

**Comment by SkytAsul** [comment]
Yup startup logs please!
No worries for the late response :)

**Comment by OakLoaf** [comment]
I lied, I do use paperweight, I was on the wrong branch

**Comment by OakLoaf** [comment]
I'm going to try doing this real quick: https://docs.papermc.io/paper/dev/userdev#compiling-to-spigot-mappings

**Comment by OakLoaf** [comment]
Can confirm, this resolved the issue

**Comment by SkytAsul** [comment]
Perfect! In the meantime, I continued working on adding support for the remapped version :)

**Comment by OakLoaf** [comment]
Just thought I'd correct the title of this to be less misleading :)

**Comment by SkytAsul** [comment]
It was HARD but _finally_: you can now use GlowingEntities on non-remapped servers!
