### ISSUE TITLE
Glowing not working with Citizens.

### ISSUE THREAD

**Issue by dom3** [SkytAsul/GlowingEntities#20]
Now, I know in a previous issue you said glowing is not really supported due to there already being a built-in glow system. But that glow system cannot do glow for individual players. Could I do it with this library? (Only one I could find)

**Comment by dom3** [comment]
Update: Found out part of the issue: when setting the colors of the npc, the last color set will set for all npcs where colors were set.
![2024-08-05_12 41 51](https://github.com/user-attachments/assets/265b8014-b051-440e-9c12-c883eca1958b)
![yuh](https://github.com/user-attachments/assets/e733b0b1-0433-43d7-a2f7-eab55963640f)
![image](https://github.com/user-attachments/assets/afc8bdb1-ea9a-4497-bb7b-5e77b6b6d7e9)

**Comment by SkytAsul** [comment]
Internally Citizens uses a lot of teams to manage the nametag visibility, collision, etc.
It seems like those teams are shared between some NPCs.
I don't think I'll be able to fix that unfortunately...

**Comment by dom3** [comment]
Found the fix, NPCs have to have unique names.
