### ISSUE TITLE
Blocks turn into shulkers

### ISSUE THREAD

**Issue by NotPatch** [SkytAsul/GlowingEntities#24]
for(Block block : getBlocksInRadius(l, radius)){
            if(block.getType().equals(Material.DIAMOND_ORE)){
                try {
                    glowingBlocks.setGlowing(block, p, ChatColor.AQUA);
                } catch (ReflectiveOperationException e) {
                    throw new [RuntimeException](http://www.google.com/search?hl=en&q=allinurl%3Adocs.oracle.com+javase+docs+api+runtimeexception)(e);
                }
            }
            if(block.getType().equals(Material.COAL_ORE)){
                try {
                    glowingBlocks.setGlowing(block, p, ChatColor.BLACK);
                } catch (ReflectiveOperationException e) {
                    throw new [RuntimeException](http://www.google.com/search?hl=en&q=allinurl%3Adocs.oracle.com+javase+docs+api+runtimeexception)(e);
                }
            }
        }

https://prnt.sc/x-XTE7KCM6gj

**Comment by SkytAsul** [comment]
Hello.
1. Which version of GlowingEntities are you using?
2. Which version of the server are you using?
3. Which version of the client?

**Comment by NotPatch** [comment]
1: 1.4
2: 1.21.1
3: 1.21.1

**Comment by SkytAsul** [comment]
Which server software? Paper, Spigot...
By the way, on your screenshot, I can't see anything 'cause everything is pitch black. Can you do it again in a clear space and send a new screenshot. Also, turn off your shaders, it may be caused by them.

**Comment by NotPatch** [comment]
![image](https://github.com/user-attachments/assets/2c784fab-f041-4e72-bd97-462921fd4394)
![image](https://github.com/user-attachments/assets/761ebdef-a68e-4c90-a2e3-704638803999)
![image](https://github.com/user-attachments/assets/dfa5a0b4-c1f2-4311-9854-a62e70bd5295)
![image](https://github.com/user-attachments/assets/9d96b67c-430c-4a0c-9736-3d100dd661ec)

It was caused by Shader.

**Comment by SkytAsul** [comment]
Too bad! I'm glad you found out. Maybe using Block Display Entities would work, you can try. If they work, I will start working on #19.
