### ISSUE TITLE
Bug: Player glowing forever after unset glowing.

### ISSUE THREAD

**Issue by Dr3amWars** [SkytAsul/GlowingEntities#25]
Hi,

I am facing a potential bug where player A glowing forever in white when I set a player A glowing in red for another player B and player B go away out of entity display reach and go back before the player A is unset glowing.
Screens step:
![2024-11-25_19 55 52](https://github.com/user-attachments/assets/008940cd-d5ed-422c-8749-f4157f8cc664)
![2024-11-25_19 55 57](https://github.com/user-attachments/assets/103f8c1e-eaa4-473e-b475-1f976784e81f)
![2024-11-25_19 56 02](https://github.com/user-attachments/assets/1c68c172-56aa-4ae6-af25-a7a26a745285)

I'm currently on a 1.19.2 spigot local server with ProtocolLib v5.0.0 plugin for other purpose and I use version 1.4 of your GlowingEntities.
Language Kotlin

Code implementations:
```kotlin
       val playerList = mutableListOf<UUID>()
       Bukkit.getScheduler().runTaskLater(
            himsgame,
            Runnable {
                playerList.forEach {
                    val player = himsgame.server.getPlayer(it) ?: return@forEach
                    himsgame.glowingEntities.unsetGlowing((player as Entity), playerExecute) // playerExecute instance of Player
                    playerList.remove(it)
                }
             },
            10*20
        )
```

**Comment by SkytAsul** [comment]
Please try without ProtocolLib and your "other purpose" plugin.

**Comment by Dr3amWars** [comment]
Hi,

I try with a test plugin and no problem. I search for information on the packet Play.Server.REL_ENTITY_MOVE but I can't access wiki.vg/Protocol. Do you have access to it? Or could this packet cause problems, if you know?

**Comment by SkytAsul** [comment]
wiki.vg seems down at the moment. You can see a recent version on archive.org though: https://web.archive.org/web/20241130183628/wiki.vg/Protocol
I don't see the relation between GlowingEntities and the Entity Move Packet. But if when using a test plugin and without ProtocolLib, GlowingEntities work correctly, I advise you to look into the other plugins.

**Comment by Dr3amWars** [comment]
Thanks you, I will check it.
