### ISSUE TITLE
Adding support for block glow

### ISSUE THREAD

**Issue by Tuchan** [SkytAsul/GlowingEntities#3]
This is by far the best "glow" API I've used. The only issue is that you can't apply glow on blocks just by using this API. You have to create shulkers and then apply glow on them, which could be supported out of the box to provide an even better user experience. You could also get a free performance boost since you wouldn't have to load all shulkers and then hide them with invisibility. If my brain works correctly, this should be achievable almost in the same way how [YAMIPA does it](https://github.com/josemmo/yamipa#how-does-it-work).

**Comment by SkytAsul** [comment]
I'm working on it, thanks for the idea!
